### ISSUE TITLE
Explicit Anchors

### ISSUE THREAD

**Issue by harjotgill** [artempyanykh/marksman#188] opened 2023-04-02 21:23 UTC
Looks like explicit anchors are not supported. 

e.g.
`### AIMDConcurrencyController {#a-i-m-d-concurrency-controller}`

Autocompletes to -
`[AIMDConcurrencyController](/reference/policies/spec.md#aimdconcurrencycontroller-a-i-m-d-concurrency-controller)`

Whereas the correct autocompletion is:
`[AIMDConcurrencyController](/reference/policies/spec.md#a-i-m-d-concurrency-controller)`

**Comment by artempyanykh** [comment] 2023-04-02 21:51
Thanks for opening this @harjotgill! I think this is a dupe of #41 (feel free to reopen if it's somehow different)

**Closed by artempyanykh** 2023-04-02 21:51 UTC
