### ISSUE TITLE
Add an option to exclude some folders

### ISSUE THREAD

**Issue by tukusejssirs** [artempyanykh/marksman#100] opened 2022-10-26 15:25 UTC
I am not sure if this is an issue of `marksman` or of [`LSP-marksman`](https://github.com/sublimelsp/LSP-marksman) which I use in Sublime Text.

---

I have noticed that `marksman` does not ignore files in `node_modules/` folder, therefore I have now log of warnings of files that are not mine and I don’t care about them.

It would be nice to provide a way to ignore/exclude files, ideally using globs (like in `.gitignore`).

**Comment by tukusejssirs** [comment] 2022-10-26 17:37
> Marksman [supports ignore files](https://github.com/artempyanykh/marksman#ignore-files).

I missed that. :wink:

> Are you saying that `node_modules` is in your `.gitignore` but is still picked up by marksman?

Yes, I have `node_modules/` in `.gitignore`.

Just to make sure I provide all needed information:

- I use Sublime Text.
- In ST, I installed [LSP](https://github.com/sublimelsp/LSP) and [`LSP-marksman`](https://github.com/sublimelsp/LSP-marksman) packages.
- I work with ST projects (workspaces) in which I have add a folder which is the root folder of the project in which all Markdown files are processed by `marksman` (via `LSP-marksman`).

Now, when I install `aedes` NPM package in that folder, in the Diagnostics Panel I can see the following logs:

```python
$root_folder/node_modules/aedes/README.md:
   27:5   warning Link to non-existent heading 'extensions' ​Marksman:2
   38:7   warning Link to non-existent heading 'benchmark-mosca' ​Marksman:2
```

**Comment by artempyanykh** [comment] 2022-10-26 19:02
Thanks for the extra context @tukusejssirs! Might be a problem with glob evaluation. Before I start investigating, could you try changing .gitignore to have `node_modules` or `node_modules/*` or some other variation and restart the server?

**Comment by tukusejssirs** [comment] 2022-10-26 20:25
I tested it with these globs, but the result is always the same:
- `node_modules`;
- `node_modules/`;
- `node_modules/*`;
- `/node_modules`;
- `/node_modules/`;
- `/node_modules/*`;
- `node_modules/aedes/docs/Aedes.md`;
- `/node_modules/aedes/docs/Aedes.md`.

After each change in `.gitignore`, I restarted the LSP server. I’ve even tested them all at once.

I also thought that the issue is in the fact that I have `node_modules/` not only in the repo root folder, but also in some subfolders, however, even when I explicitly add them with path to that folder (e.g. `a/b/node_modules/`), even then the warnings/errors are reported.

**Comment by artempyanykh** [comment] 2022-10-26 22:29
Thanks for trying @tukusejssirs! My original motivation for adding ignores support was exactly to avoid indexing `node_modules` while working with docusaurus docs. And it worked for me in neovim. But apparently something is wrong.

I'll look into it. Meantime, could you tell me your `marksman --version`? Also, is the repository you're working on OSS?

**Comment by artempyanykh** [comment] 2022-10-27 20:01
I reproduced an issue. It's a problem with glob patterns evaluation. The fix is in progress.

**Comment by tukusejssirs** [comment] 2022-10-27 20:23
Sorry for late reply.

The version I use is `1.0.0-1a3998f`. I use it on Arch Linux.

It can be reproduced on any repository after installing any NPM package that contains some issues in its Markdown files (e.s. `aedes` package). However, that is irrelevant, as you seem to found the culprit. :+1: :pray:

**Comment by artempyanykh** [comment] 2022-10-30 14:29
@tukusejssirs please try this version https://github.com/artempyanykh/marksman/releases/tag/2022-10-30 and let me know if it helps.

**Comment by tukusejssirs** [comment] 2022-10-30 14:40
@artempyanykh, it seems to be fixed, thanks! :pray:

Just a note: GitHub does not auto-closes issues when `fix`/`resolve` (et al) keywords are in release notes; it does so when the keywords are in commit messages. Maybe that was your intention, but I felt it might be a good idea make sure you know about it. :wink:

**Comment by artempyanykh** [comment] 2022-10-30 16:58
> it seems to be fixed, thanks! 🙏

Glad to hear that!

> GitHub does not auto-closes issues when fix/resolve (et al) keywords are in release notes

Thank you, I'm aware of that. I wanted to confirm with you that the issue is indeed resolved before closing it.

**Closed by artempyanykh** 2022-10-30 16:58 UTC
Labels: bug
