### ISSUE TITLE
Duplicate headers error

### ISSUE THREAD

**Issue by rchl** [artempyanykh/marksman#65] opened 2022-08-29 11:17 UTC
In a document like:

```
# Changelog

## [14.0]
### Breaking
- foo

## [13.0]
### Breaking
- bar
```

The second `Breaking` header is reported as duplicate. I think it doesn't make sense since it's under different parent header.

**Comment by artempyanykh** [comment] 2022-08-29 12:42
@rchl thanks for reporting. This is a known problem but the solution is not obvious to me. The gist of the issue is that when you have an anchor link [xxx](doc.md#heading) the heading is not qualified by its path but only by its name. This is in particular what GitHub expects.
GH internally deals with this by adding a -1, -2, -n suffix but then it's super easy to mess up the links when you add yet another heading.

Perhaps the severity should be downgraded to a warning or maybe we need a way to turn off this diagnostics for a file.

Anyhow, I'm open to more ideas.

**Comment by artempyanykh** [comment] 2022-08-29 12:55
One potential solution could be to turn "duplicate heading" error into an "ambiguous link" error. This way when there are no links to the heading, no diagnostics will be raised.

**Comment by rchl** [comment] 2022-08-29 19:17
That sounds good to me.

But I also want to point you at https://raw.githubusercontent.com/rust-lang/rust-analyzer/bd7dfac5ebbd8ba3bd63384000759fb4bb49b329/docs/dev/README.md which also reports duplicate headers even though those don't seem to be duplicated.

**Comment by artempyanykh** [comment] 2022-08-29 19:39
> But I also want to point you at https://raw.githubusercontent.com/rust-lang/rust-analyzer/bd7dfac5ebbd8ba3bd63384000759fb4bb49b329/docs/dev/README.md which also reports duplicate headers even though those don't seem to be duplicated.

@rchl the problem there is a "duplicate **title**". The expectation is that there should be just one H1 header aka the title that _names the document_ and then the rest of the headings are H2 -- H5. When there are multiple titles in the document you can't unambiguously use e.g. wiki-links. 

But then again, this problem seems to have the same treatment  -- just redo heading diagnostics as "ambiguous link" diagnostics. The side-effect is that if you're unaware of the requirements on headings, wiki-link- and cross-doc completion can act really weirdly. But perhaps this is a better UX anyway then expecting random markdown document to conform to the ideal document structure.

**Comment by rchl** [comment] 2022-08-29 19:42
I'm not the best person to discuss that with as I'm not really that familiar with this stuff and frankly those issues don't typically matter in markdown files that I'm working with.

That said, would it make sense for the "duplicate title" error to be a bit more descriptive? If it would say, for example, "Duplicate first-level header"

**Comment by artempyanykh** [comment] 2022-08-31 20:41
Yeah, that's fine. I think high-level ask is clear. I'll look into improving diagnostics UX.

**Comment by artempyanykh** [comment] 2022-09-03 15:54
Resolved in https://github.com/artempyanykh/marksman/releases/tag/2022-09-03

**Closed by artempyanykh** 2022-09-03 15:54 UTC
Labels: bad UX
