### ISSUE TITLE
Crash when reading logseq-specific markdown files

### ISSUE THREAD

**Issue by mrene** [artempyanykh/marksman#156] opened 2023-02-08 00:37 UTC
The following exception occurs when trying to parse logseq markdown files that have additional properties.

```
Unhandled exception: System.AggregateException: One or more errors occurred. (Exception has been thrown by the target of an invocation.)
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentOutOfRangeException: Index and length must refer to a location within the string. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Marksman.Parser.Markdown.scrapeText(Text text) in /build/source/Marksman/Parser.fs:line 172
   at Marksman.Parser.parseText(Text text) in /build/source/Marksman/Parser.fs:line 392
   at Marksman.Workspace.DocModule.mk(PathUri path, RootPath rootPath, FSharpOption`1 version, Text text) in /build/source/Marksman/Workspace.fs:line 45
```

In logseq, blocks (bullet points) and markdown files can have properties, which are structured as `identifier:: contents`. It will save the last filter settings and block states (collapsed, expanded) into these properties.

In this case, a file named `inbox.md`  was causing the crash and contained the following:

```
filters:: {"work" true}

-
```

Note that it crashes even if the file isn't the file being browsed as it's trying to index the full directory.

**Comment by artempyanykh** [comment] 2023-02-08 10:02
Thanks for reporting this @mrene! 
Unfortunately, so far I couldn't reproduce locally with the provided text.

Could you tell me what is the output of `marksman --version` and what text editor you use it with? Could you also check the file for any special symbols (e.g. a non-breaking space)?

The stack trace points to an error in header parsing, but I'm not sure what in the contents of the file might cause this.

**Comment by mrene** [comment] 2023-02-08 13:08
Thanks for looking at this so quickly!

I'm using neovim on NIxOS, I tried the latest commit on the main branch ([ecef5e8](https://github.com/artempyanykh/marksman/commit/ecef5e8f8fb88bd4e6b952f985517affd45bb384)) and it would crash as well.

Here's the [file](https://gist.githubusercontent.com/mrene/8cdf74a69945d4143ca38067fee6dbfd/raw/b00e65cb5744dfca70615d28d3f12fc7ab5c33f7/inbox.md) that reproduces the crash, maybe it's sensitive to some non-visible whitespace content. Starting marksman in an empty dir with only that file (and .git so it finds a root) crashes reliably

**Comment by artempyanykh** [comment] 2023-02-09 10:02
@mrene thank you! I could reproduce the issue.

**Comment by artempyanykh** [comment] 2023-02-11 17:28
The issue is in one of Marksman's dependencies. I submitted a fix, let's see if/when it gets merged.

@mrene as a workaround just add a newline after the last dash `-`. Note that the following snippet
```
-
-
```
is treated as a 2nd level *heading* with the text `-` according to the [markdown spec (see setext headings)](https://spec.commonmark.org/0.30/#setext-headings).

If these logseq properties are always at the top of the file, they could be treated similarly to a YAML front-matter.

**Comment by mrene** [comment] 2023-02-13 01:28
Thanks for the fix! These properties can be in any block (denoted by `- `) so I don't think it fits the frontmatter concept. They use these to remember which block is collapsed and which one is expanded (amongst other things, these are user-customizable and you can use them to query for things)

**Comment by artempyanykh** [comment] 2023-02-18 11:03
I see! @mrene could you provide a more complete example of a logseq markdown document with a couple of these blocks? I think adding an option to disable setext-headings would be an easy way to avoid problems with logseq markdown, but I'd need to see a more complete example first.

**Comment by mrene** [comment] 2023-02-18 14:01
Their own docs are written using this format, here's a [a](https://github.com/logseq/docs/blob/master/pages/examples.md) [few](https://github.com/logseq/docs/blob/master/pages/Queries.md) [examples](https://github.com/logseq/docs/blob/master/pages/Markdown.md)

**Comment by artempyanykh** [comment] 2023-02-19 10:17
@mrene thank you! So, these properties are really just lines of the form `bar:: baz`. They are not delimited with 2 single dash lines, right?
```
-
-
```

If so, I think we should be good.

**Comment by mrene** [comment] 2023-02-19 12:31
Oh no the two single dash lines just happen by accident when you hit enter in an empty page (they all start with a single one), props are just key:: value

**Comment by artempyanykh** [comment] 2023-02-19 15:15
Cool! Than we're good here.

**Closed by artempyanykh** 2023-02-19 15:15 UTC
Labels: bug
